aws:
  url: "http://localhost:9000"
  accessKey: "ElexirID"
  secretKey: "987654321"

broker:
  host: "localhost"
  port: "5671"
  user: "test"
  password: "test"
  vhost: "/test"
  exchange: "localega.v1"
  routingKey: "files.inbox"
  ssl: "true"
  cacert: "./dummy/certs/ca.crt"
  clientcert: "./dummy/certs/client.crt"
  clientkey: "./dummy/certs/client.key"

server:
  cert: "./dummy/certs/proxy.crt"
  key: "./dummy/certs/proxy.key"
