aws:
  url: "https://localhost:9000"
  accessKey: "ElexirID"
  secretKey: "987654321"
  bucket: "test"
  region: ""

broker:
  host: "localhost"
  port: "5671"
  user: "test"
  password: "test"
  vhost: "/test"
  exchange: "localega.v1"
  routingKey: "files.inbox"
  ssl: "true"
  cacert: "./dummy/certs/ca.crt"
  clientCert: "./dummy/certs/client.crt"
  clientKey: "./dummy/certs/client.key"
# If the FQDN and hostname of the broker differ
# serverName can be set to the SAN name in the certificate
  #  serverName: ""

server:
  cert: "./dummy/certs/proxy.crt"
  key: "./dummy/certs/proxy.key"
