version: "3.7"
services:
  s3_backend:
    command: server /data
    container_name: s3
    environment:
      - MINIO_ACCESS_KEY=ElexirID
      - MINIO_SECRET_KEY=987654321
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    ports:
      - "9000:9000"
    volumes:
      - "/tmp/data:/data"
  mq_server:
    container_name: mq
    image: rabbitmq:3.7.8-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./defs.json:/etc/rabbitmq/defs.json
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 30s
      timeout: 20s
      retries: 3
  s3_proxy:
    build: ../
    image: nbisweden/s3inbox
    container_name: proxy
    depends_on:
      - mq_server
      - s3_backend
    environment:
      - AWS_URL=http://s3:9000
      - AWS_ACCESS_KEY=ElexirID
      - AWS_SECRET_KEY=987654321
      - BROKER_HOST=mq
      - BROKER_USER=test
      - BROKER_PASSWORD=test
      - BROKER_PORT=5672
      - BROKER_VHOST=/test
      - BROKER_EXCHANGE=localega.v1
      - BROKER_ROUTINGKEY=files.inbox
    ports:
      - "8000:8000"
